language: rust
# cache: cargo
dist: trusty
sudo: true
os:
  - linux
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libbfd-dev
    - binutils-dev
    - libiberty-dev
    - g++
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  - rust: beta
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
- sh tools/install-kcov.sh
- cargo install cargo-kcov
script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test
- cargo kcov --verbose --no-clean-rebuild --lib --coveralls
