language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  - rust: beta
build:
  - cargo clean
  - cargo test
cache:
  cargo: true
  directories:
  - deps
script:
  - make test
