language: rust
cache:
  - cargo
  - apt
dist: trusty
# https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch
group: deprecated-2017Q2
sudo: true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libbfd-dev
    - binutils-dev
    - libiberty-dev
    - g++
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  - rust: beta
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
- which kcov || tools/install-cargo-kcov.sh
script:
- cargo fmt -- --write-mode=diff
- cargo build
- cargo test
after_success:
- tools/coveralls.sh
