[package]
name = "to-directory"
version = "2.0.1"
authors = ["Jason Campbell <jason@artifact.sh>"]
description = "[EXPERIMENTAL] A CLI utility for bookmarking directories with tab completion."
homepage = "https://github.com/jxson/to-rs"
readme = "README.md"
keywords = []
license = "ISC"

[[bin]]
name = "to"

[dependencies]
clap = "2.1.2"
rustc-serialize = "0.3.18"
bincode = "0.5.1"
