[package]
name = "to-directory"
version = "0.1.0"
authors = ["Jason Campbell <jason@artifact.sh>"]
description = "EXPERIMENTAL - A CLI utility for bookmarking directories with tab completion."
homepage = "https://github.com/jxson/to-directory"
readme = "README.md"
keywords = []
license = "ISC"

[[bin]]
name = "to-directory"

[dependencies]
clap = { version = "2.6.0", features = [ "yaml" ] }
rustc-serialize = "0.3.18"
bincode = "0.5.1"
time = "0.1.35"
