[package]
name = "to-directory"
version = "0.1.0"
authors = ["Jason Campbell <jason@artifact.sh>"]
description = "EXPERIMENTAL - A CLI utility for bookmarking directories with tab completion."
homepage = "https://github.com/jxson/to-directory"
readme = "README.md"
keywords = []
license = "ISC"

[[bin]]
name = "to-directory"

# The library is only used for tests.
[lib]
name = "to"
path = "src/lib.rs"

[dependencies]
chrono = "0.3.0"
clap = "2.20.0"
error-chain = "0.7.2"
slog = "~2.0.0-1"
slog-json = "~2.0.0-1"
slog-stream = "1.2.0"
serde = "0.9.11"
serde_derive = "0.9.11"
bincode = "1.0.0-alpha4"
time = "0.1.36"
indoc = "0.1"
